apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-iti
spec:
  selector:
    matchLabels:
      run: nodejs-iti
  replicas: 2
  template:
    metadata:
      labels:
        run: nodejs-iti
    spec:
      containers:
      - name: nodejs-iti
        image: 139646/jenkins-nodejs-test
        ports:
        - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: nodejs-iti
  labels:
    run: nodejs-iti
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: nodejs-iti
